name: Merge branches 
on: 
  push: 
    branches: 
      - uat 
jobs: 
  merge: 
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout code 
      uses: actions/checkout@v2 
    - name: test of merge 
      run: |
        echo "running merge workflow"
        echo "testing"
        git checkout uat
        git checkout -b main
        git pull origin main
        git checkout uat 
        git merge main
        git push origin uat 